### PR TITLE
Added support for current Ecobee models and an optional update frequency

### PR DESCRIPTION
**Pull request by rhdny**
Added support for apolloSmart and nikeSmart models. Added a configurable update frequency that defaults to 30 seconds to be consistent with the original code. I am only tracking humidity (the only missing visible metric in Ecobee's HomeKit integration) and wanted to adjust the frequency to 120 seconds given how slowly the metric changes.

### CODE REVIEW

**Comment by vojtamolda** [comment]
All looks good. Thank you!

**Comment by rhdny** [comment]
Quick follow up question, does the update need to be published to npm, so that it shows up in the homebridge plugin list? 0.1.5 is still there. No worries for me as I manually updated my installation but figured I'd ask...

**Comment by vojtamolda** [comment]
Sorry and thanks for the reminder. It's been a while since I worked with `npm` so I forgot to publish the package and make a release.

You should now be able to get version `0.1.6` which has your changes.

**Comment by rhdny** [comment]
No worries! I ran the plugin update via Homebridge this morning and all is good. Thanks again!

**Comment by vojtamolda** [comment]
Pefect!

**Pull request merged**
